# Makefile created by mkmf $Id: mkmf,v 14.0 2007/03/20 22:13:27 fms Exp $ 

include ./gfortran_mac.inc


.DEFAULT:
	-touch $@
all: dEdd_obs.x
dEdd_obs.o: /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/dEdd_obs.F90 icepack_shortwave.o icepack_parameters.o
	$(FC) $(CPPDEFS) $(CPPFLAGS) $(FFLAGS) $(OTHERFLAGS) -c	/Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/dEdd_obs.F90
icepack_kinds.o: /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_kinds.F90
	$(FC) $(CPPDEFS) $(CPPFLAGS) $(FFLAGS) $(OTHERFLAGS) -c	/Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_kinds.F90
icepack_orbital.o: /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_orbital.F90 icepack_kinds.o icepack_parameters.o
	$(FC) $(CPPDEFS) $(CPPFLAGS) $(FFLAGS) $(OTHERFLAGS) -c	/Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_orbital.F90
icepack_parameters.o: /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_parameters.F90 icepack_kinds.o
	$(FC) $(CPPDEFS) $(CPPFLAGS) $(FFLAGS) $(OTHERFLAGS) -c	/Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_parameters.F90
icepack_shortwave.o: /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_shortwave.F90 icepack_kinds.o icepack_parameters.o icepack_tracers.o icepack_orbital.o
	$(FC) $(CPPDEFS) $(CPPFLAGS) $(FFLAGS) $(OTHERFLAGS) -c	/Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_shortwave.F90
icepack_tracers.o: /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_tracers.F90 icepack_kinds.o icepack_parameters.o
	$(FC) $(CPPDEFS) $(CPPFLAGS) $(FFLAGS) $(OTHERFLAGS) -c	/Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_tracers.F90
./icepack_parameters.F90: /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_parameters.F90
	cp /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_parameters.F90 .
./dEdd_obs.F90: /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/dEdd_obs.F90
	cp /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/dEdd_obs.F90 .
./icepack_kinds.F90: /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_kinds.F90
	cp /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_kinds.F90 .
./icepack_orbital.F90: /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_orbital.F90
	cp /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_orbital.F90 .
./icepack_tracers.F90: /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_tracers.F90
	cp /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_tracers.F90 .
./icepack_shortwave.F90: /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_shortwave.F90
	cp /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_shortwave.F90 .
SRC = /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/dEdd_obs.F90 /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_shortwave.F90 /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_parameters.F90 /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_orbital.F90 /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_tracers.F90 /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_kinds.F90
OBJ = dEdd_obs.o icepack_shortwave.o icepack_parameters.o icepack_orbital.o icepack_tracers.o icepack_kinds.o
OFF = /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_parameters.F90 /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/dEdd_obs.F90 /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_kinds.F90 /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_orbital.F90 /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_tracers.F90 /Users/ioulianikolskaia/Boulot/SCIENCE/my_RESEARCH/SEA_ICE_OPTICS/DELTA_EDDINGTON/dEdd_obs/SOURCE/icepack_shortwave.F90
clean: neat
	-rm -f .cppdefs *.com *.mod $(OBJ) dEdd_obs.x
neat:
	-rm -f $(TMPFILES)
localize: $(OFF)
	cp $(OFF) .
TAGS: $(SRC)
	etags $(SRC)
tags: $(SRC)
	ctags $(SRC)
dEdd_obs.x: $(OBJ) 
	$(FC) $(LD) $(OBJ) -o dEdd_obs.x  $(LDFLAGS)
